### ISSUE TITLE
gulp plugins should do one thing

### ISSUE THREAD

**Issue by sindresorhus** [kmalakoff/gulp-compile-js#1]
There's already plugins for coffee, jade and stylus, so i don't see the point of this plugin.

https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md

> Your plugin should only do one thing, and do it well.

// @contra

**Comment by phated** [comment]
This plugin has so much code smell.  Please remove this package or follow the guidelines.

Gulp is not Grunt, don't try to force those paradigms on it.

**Comment by sindresorhus** [comment]
@kmalakoff ping

**Comment by kmalakoff** [comment]
Sorry, not interested in being registered with the gulp registry.
